name: 1314c6eb-31b0-41c6-bd8f-a571cc700d58
displayName: Rest API 1
type: restapi
options:
  baseURL: ''
  headers:
    - - ''
      - ''
  urlparams:
    - - ''
      - ''
  auth0_domain: ''
  oauth2_scope: ''
  auth0_clientID: ''
  authentication: ''
  basic_password: ''
  basic_username: ''
  oauth2_auth_url: ''
  cookiesToForward: []
  oauth2_client_id: ''
  forwardAllCookies: false
  auth0_clientSecret: ''
  extraBodyKeyValues:
    - - ''
      - ''
  verify_session_url: ''
  oauth2_access_token: ''
  oauth2_callback_url: >-
    http://ec2-54-244-45-22.us-west-2.compute.amazonaws.com:3000/oauth/user/oauthcallback
  session_cookie_name: ''
  oauth2_client_secret: ''
  oauth2_refresh_token: ''
  auth0_custom_audience: ''
  oauth1_signature_method: HMAC-SHA1
  oauth2_access_token_url: ''
updatedAt: 2021-03-11T02:39:36.156Z
createdAt: 2021-03-11T02:39:36.156Z
host: null
port: null
databaseName: null
databaseUsername: null
databasePassword: null
ssl: null
editPrivilege: null
environment: production
dynamicallyQueryable: false
version: '1.0'
