name: 3c783985-c44a-4895-82e7-5e380193112d
displayName: Internal Shell Script
type: shell
options:
  shellHost: ec2-54-244-45-22.us-west-2.compute.amazonaws.com
  shellPort: '22'
updatedAt: 2021-03-11T07:44:13.104Z
createdAt: 2021-03-11T07:44:13.104Z
host: null
port: null
databaseName: null
databaseUsername: null
databasePassword: null
ssl: null
editPrivilege: null
environment: production
dynamicallyQueryable: false
version: '1.0'
