createdAt: 2021-03-11 02:39:36.156000+00:00
databaseName: null
databasePassword: null
databaseUsername: null
displayName: resource4
dynamicallyQueryable: false
editPrivilege: null
environment: production
host: null
name: !!python/object:uuid.UUID
  int: 89500493895207522810015213539153208766
options:
  auth0_clientID: ''
  auth0_clientSecret: ''
  auth0_custom_audience: ''
  auth0_domain: ''
  authentication: ''
  baseURL: ''
  basic_password: ''
  basic_username: ''
  cookiesToForward: []
  extraBodyKeyValues:
  - - ''
    - ''
  forwardAllCookies: false
  headers:
  - - ''
    - ''
  oauth1_signature_method: HMAC-SHA1
  oauth2_access_token: ''
  oauth2_access_token_url: ''
  oauth2_auth_url: ''
  oauth2_callback_url: http://ec2-54-244-45-22.us-west-2.compute.amazonaws.com:3000/oauth/user/oauthcallback
  oauth2_client_id: ''
  oauth2_client_secret: ''
  oauth2_refresh_token: ''
  oauth2_scope: ''
  session_cookie_name: ''
  urlparams:
  - - ''
    - ''
  verify_session_url: ''
port: null
ssl: null
type: restapi
updatedAt: 2021-03-11 02:39:36.156000+00:00
version: '1.0'
